### ISSUE TITLE
We do not give access to the full alert properties in context variable; name is confusing

### ISSUE THREAD

**Issue by dbbaughe** [opendistro-for-elasticsearch/alerting#25]
Currently the alert in the context variable only has four of it's properties.
On [documentation](https://opendistro.github.io/for-elasticsearch-docs/docs/alerting/monitors/#available-variables) we mention a few properties which are missing

> The current, active alert (if it exists). Includes ctx.alert.id, ctx.alert.version, and ctx.alert.isAcknowledged. Null if no alert is active.

It's also confusing since people expect this to be the new alert being generated instead of the existing alert (if it exists). Perhaps we should rename this variable.

Simple change to make for adding properties [here](https://github.com/opendistro-for-elasticsearch/alerting/blob/master/alerting/src/main/kotlin/com/amazon/opendistroforelasticsearch/alerting/model/Alert.kt#L171)

**Comment by dbbaughe** [comment]
https://github.com/opendistro-for-elasticsearch/alerting/issues/16

**Comment by vinooamzn** [comment]
> It's also confusing since people expect this to be the new alert being generated instead of the existing alert (if it exists). Perhaps we should rename this variable.
> 
 There's a bit of chicken and egg here since we don't save the alert until after the notifications are sent (so that we can capture errors in sending the notification in the alert). What's the use-case for exposing the new alert being generated to the action? From #16, it looks like the reporter would like to auto-acknowledge the alert immediately after it's sent which might really be a need for suppressing repeated notifications after the first one is sent (i.e. time based notification suppression)

**Comment by dbbaughe** [comment]
Yes, noticed that issue when looking through code which is why I think we can at least rename the current ctx.alert to something that makes it easier to understand that it is not in fact the alert being created.

@aradhell,
Could you elaborate on your use case regarding sending the alert.id? Are you automatically acknowledging the alert immediately or constructing a URL to click that will acknowledge the alert?

**Comment by aradhell** [comment]
@dbbaughe  I am trying to build an URL with the alert.id to acknowledge it by clicking this URL.

My use case,
We have different type of alerts. And some of them related to Operations dept. or any other departments not related to IT/development. We need to send them human readable emails or notifications with the Acknowledge URL, so they will simply click it and take the responsibility or needed actions and alarm wont repeat anymore. 

+ auto acknowledge is also a good point.

**Comment by vinooamzn** [comment]
The fix for including `ctx.alert.id` and other missing fields in the action script has been merged to master.

**Comment by elfisher** [comment]
@vinooamzn let's add the link to the PR that fixed the issue in a comment here and close the issue. Thanks!

**Comment by vinooamzn** [comment]
This was fixed in #26.

**Comment by aradhell** [comment]
@dbbaughe Hi, I updated alerting to 0.8 but still having the same message context. Is there anything else that I should do ?

**Comment by dbbaughe** [comment]
@aradhell 

It looks like this was included in the 0.9 release
https://github.com/opendistro-for-elasticsearch/alerting/releases

**Comment by aradhell** [comment]
oh sorry, I will try and let you know, thanks!

**Comment by aradhell** [comment]
Hi @dbbaughe, first alert object ( alert notification context.alert ) still appearing as null but the second one including the id now. Thanks!

`"alert":null`

`{
  "alert": {
    "acknowledged_time": null,
    "id": "4NtKbWoB9FfidGtYx2M1",
    "version": -1,
    "end_time": null,
    "error_message": null,
    "last_notification_time": 1556611778157,
    "severity": "1",
    "start_time": 1556611778157,
    "state": "ACTIVE"
  }
}`

**Comment by dbbaughe** [comment]
Hi @aradhell,

This makes sense, the alert on the context variable is the "existing" alert **if** there is one. For the very first alert, there is no existing alert so it will be null. For the second alert/notification, the existing alert is the first one that executed before it.

**Comment by dbbaughe** [comment]
@aradhell 
I have created an issue which would solve the problem for the first alert here:
https://github.com/opendistro-for-elasticsearch/alerting/issues/45
